# Generated by Django 3.1.1 on 2020-11-21 09:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('injury_type', models.CharField(max_length=20)),
                ('injury_description', models.CharField(max_length=200)),
                ('doctor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
                ('hospital', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.hospital')),
                ('patient', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
    ]
