# Generated by Django 3.1.1 on 2020-11-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201121_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='injury_description',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='injury_type',
        ),
    ]
