# Generated by Django 3.1.1 on 2020-11-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201121_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
