# Generated by Django 3.1.1 on 2020-11-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201121_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
