# Generated by Django 3.1.1 on 2020-11-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201121_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
