# Generated by Django 3.1.1 on 2020-11-21 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20201121_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.hospital'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='injury_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='treatment',
            name='injury_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
